
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__direction_client_glue_h__proxy__H__
#define __sdbuscpp__direction_client_glue_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace gspine {

class Gesture_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.gspine.Gesture";

protected:
    Gesture_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
        proxy_.uponSignal("touchEvent").onInterface(INTERFACE_NAME).call([this](const std::string& direction){ this->onTouchEvent(direction); });
    }

    ~Gesture_proxy() = default;

    virtual void onTouchEvent(const std::string& direction) = 0;

private:
    sdbus::IProxy& proxy_;
};

}} // namespaces

#endif
